In [4]:
import numpy as np

# 1. Create 2-D matrices using NumPy
matrix_A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix_B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print(matrix_A)
print(matrix_B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [5]:
# 2. Verify the conditions for matrix addition (same dimensions)
add_matrices = matrix_A.shape == matrix_B.shape
print(add_matrices)

True


In [11]:
# 3. Perform matrix addition
if add_matrices:
    matrix_addition_result = np.add(matrix_A, matrix_B)
else:
    matrix_addition_result = None
    
if matrix_addition_result is not None:
    print("Matrix Addition Result:\n", matrix_addition_result)
else:
    print("Matrix addition not possible due to different dimensions.")

Matrix Addition Result:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [8]:
# 4. Compute the transpose of one of your matrices and perform matrix multiplication with its original matrix
matrix_A_transpose = np.transpose(matrix_A)
matrix_multiplication = np.matmul(matrix_A, matrix_A_transpose)
print(matrix_A_transpose)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
print(matrix_multiplication)

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
